# Generated by Django 5.0 on 2024-01-27 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('img', models.ImageField(upload_to='')),
                ('type', models.CharField(choices=[('python', 'Python'), ('django', 'Django'), ('backend', 'Backend'), ('frontend', 'Frontend')], default='python', max_length=20, verbose_name='Type of news')),
                ('text_news', models.TextField(verbose_name='Text news')),
                ('date', models.DateTimeField(default=datetime.datetime(2024, 1, 27, 15, 59, 36, 926830), verbose_name='Date')),
            ],
            options={
                'verbose_name': 'News',
                'ordering': ['-date', 'title'],
            },
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
