# Generated by Django 5.0 on 2024-01-27 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_newsmodel_delete_test'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsmodel',
            options={'ordering': ['-date', 'title'], 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 27, 16, 20, 8, 945964), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='img',
            field=models.ImageField(upload_to='test_django/images_from_user'),
        ),
    ]
