# Generated by Django 5.0 on 2024-01-27 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_newsmodel_options_alter_newsmodel_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 27, 16, 38, 9, 800543), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='img',
            field=models.ImageField(upload_to='test_django/images_from_user/%Y/%m/%d/'),
        ),
    ]
