# Generated by Django 5.0.1 on 2024-01-31 13:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_newsmodel_author_alter_newsmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 31, 16, 45, 20, 97106), verbose_name='Date'),
        ),
    ]
