# Generated by Django 5.0.1 on 2024-02-03 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_newsmodel_author_alter_newsmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 3, 16, 32, 6, 105189), verbose_name='Date'),
        ),
    ]
