# Generated by Django 5.0.1 on 2024-02-11 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_newsmodel_author_alter_newsmodel_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 11, 17, 16, 54, 679681), verbose_name='Date'),
        ),
    ]
