# Generated by Django 5.0.1 on 2024-02-17 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_newsmodel_date_commentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 17, 20, 26, 51, 709493), verbose_name='Date'),
        ),
    ]
