# Generated by Django 5.0.1 on 2024-02-18 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_newsmodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 18, 15, 56, 42, 384258), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='text',
            field=models.TextField(verbose_name='Text comment'),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 18, 15, 56, 42, 384258), verbose_name='Date'),
        ),
    ]
