# Generated by Django 5.0.1 on 2024-02-18 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_commentmodel_date_alter_newsmodel_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentmodel',
            options={'ordering': ['-date']},
        ),
    ]
